# Site settings
title: Ben Bolte's Blog
email: bkbolte18@gmail.com
description: >
  Another machine learning blog.
baseurl: ""
url: "http://codekansas.github.io" 
github_username: codekansas
twitter_username: code__kansas

# Build settings
markdown: kramdown
permalink: /blog/:year/:title:output_ext
