# Site settings
title: ETZQ
email: bkbolte18@gmail.com
description: >
  Blog about miscellaneous stuff
baseurl: ""
url: "http://codekansas.github.io" 
github_username: codekansas

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
