# Site settings
title: ETZQ
email: bkbolte18@gmail.com
description: >
  The website of Ben Bolte
baseurl: ""
url: "http://codekansas.github.io" 
github_username: codekansas
twitter_username: code__kansas

# Build settings
markdown: kramdown
permalink: /blog/:year/:title:output_ext

