# Site settings
title: Ben's Blog
email: bkbolte18@gmail.com
description: >
  s = 's = %r; print(s%%s)'; print(s%s)
baseurl: ""
url: "http://codekansas.github.io" 
github_username: codekansas
twitter_username: code__kansas

# Build settings
markdown: kramdown
permalink: /blog/:year/:title:output_ext